### ISSUE TITLE
Add testnet mainnet switch to bridge

### ISSUE THREAD

**Issue by yarkinwho** [eosnetworkfoundation/evm-bridge-frontend#2]
Moved from https://github.com/eosnetworkfoundation/eos-evm/issues/452

**Comment by Joshua2Mars** [comment]
Something need to track here to optimize: on the testnet page, the menu directly displays "Testnet", and users can toggle to the mainnet by selecting from the dropdown menu. On the mainnet, the menu directly displays "Mainnet", and users can toggle to the testnet by selecting from the dropdown menu.
