### ISSUE TITLE
Disconnect wallet from Bridge

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/evm-bridge-frontend#24]
##### User story:

As a user, I want to be able to disconnect my wallet after connecting it to a bridge so that I may connect a different wallet.

##### Requirements:

1. When a when a user has a wallet connected to the Bridge, they can select their wallet address to show a dropdown list of options
    1. If a user selects the copy address option, their address is added to their clipboard
    2. If a user selects the view on block explorer option, the page for that wallet address activity opens in a new tab
2. When a user selects the Disconnect option, they are shown a confirmation prompt
    3. If a user selects the cancel option, the prompt closes and no action is taken
3. When a user selects the confirmation option to disconnect, their wallet is disconnected from the bridge

**Comment by stephenpdeos** [comment]
May be resolved by https://github.com/eosnetworkfoundation/evm-bridge-frontend/issues/35

**Comment by yarkinwho** [comment]
Yes, it should be solved by #35
