### ISSUE TITLE
Expose Korean and Chinese Translations

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/evm-bridge-frontend#30]
1. Get translations from partners for Korean and Chinese locales.

2. Update
- [ ] https://github.com/eosnetworkfoundation/evm-bridge-frontend/blob/main/src/App.vue
- [ ] https://github.com/eosnetworkfoundation/evm-bridge-frontend/blob/main/src/i18n.js

**Comment by arhag** [comment]
Reopening since this is for 0.8.1 but it was not merged into the `release/0.8` branch.

**Comment by arhag** [comment]
Decided to move to 0.9.0 milestone so this is actually done now.
