### ISSUE TITLE
Block all the CEX address from FE of Trustless bridge

### ISSUE THREAD

**Issue by yarkinwho** [eosnetworkfoundation/evm-bridge-frontend#4]
Now we confirme:
Supported CEX:

Coinbase(eos address: coinbasebase)
Huobi Global(eos address: huobideposit, the amount should be greater than 0.1EOS)
Unsupported CEX:

Kucoin: kucoindoteos
Binance: binancecleos
OKX: okbtothemoon
Bitget: bitgeteosdep
Bybit: bybitdeposit
Gate: gateiowallet

We should:
1 block all unsupported CEX
2 Add a line of warning about minimum amount requirement

Moved from https://github.com/eosnetworkfoundation/eos-evm/issues/496

**Comment by Joshua2Mars** [comment]
For supported CEX:
1. Users are able to tranfer EOS to their CEX account.
2. A reminder to user: "Please note the minimum transfer limit to CEX"

For unsupported CEX:
1. Users are not able to click the tranfer buttons with a notice: "Unsupported CEX to transfer."

**Comment by Joshua2Mars** [comment]
This feature needs to be deployed on the testnet for more community members to test and ensure that the functionality meets expectations before further modifications are made. I will roll it over next Sprint to be confirmed.

**Comment by Joshua2Mars** [comment]
Supported CEX:

Coinbase(eos address: coinbasebase)
Huobi Global(eos address: huobideposit, the amount should be greater than 0.1EOS)
Unsupported CEX:

Kucoin: kucoindoteos
Binance: binancecleos
Binance2: eosbndeposit 
OKX: okbtothemoon
Bitget: bitgeteosdep
Bybit: bybitdeposit
Gate: gateiowallet
