### ISSUE TITLE
Remove gas fee estimation from FE design

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/evm-bridge-frontend#51]
Because a users wallet will present the correct associated gas fee, we do not need to calculate this for them any longer as part of bridge experience.

Instead, we'd like to communicate the following
- Amount of token being used + gas fee
- Amount of token that will be received

**Comment by yarkinwho** [comment]
Discussed with Joshua:

As we do not have egress fee, we will do things like this for now: 
EOS: 
Gas Fee: ~0.0032 EOS
USDT: 
Gas Fee: ~0.016 EOS
Bridge Fee: 0.01 EOS

Note those number will be hardcoded number. 

Basically that's giving the user some relatively high estimate to give user a rough idea about the gas fee. 

And we want this in 0.9rc2
