### ISSUE TITLE
Wallet Connect modal for switching networks design

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/evm-bridge-frontend#52]
For mobile wallets, if EOS EVM is not supported, the attempt to connect to this network will fail. We need a more informative modal designed for this instance.

**Comment by stephenpdeos** [comment]
We've detected that the wallet you are attempting to use has not been configured to support EOS EVM. Please use the following network information to add the network or visit our [documentation page](https://docs.eosnetwork.com/evm/quick-start/setup-metamask) for more details

Mainnet

<details><summary><b>Mainnet</b></summary><p>

- Network Name: EOS EVM
- Chain ID: 17777
- New RPC URL: https://api.evm.eosnetwork.com/
- Currency Symbol: EOS
- Block Explorer URL (Optional): https://explorer.evm.eosnetwork.com/
- Token Bridge: https://bridge.evm.eosnetwork.com/   

</p></details>


<details><summary><b>Testnet</b></summary><p>

- Network Name: EOS EVM Testnet
- Chain ID: 15557
- New RPC URL: https://api.testnet.evm.eosnetwork.com/
- Currency Symbol: EOS
- Block Explorer URL (Optional): https://explorer.testnet.evm.eosnetwork.com/
- Token Bridge: https://bridge.testnet.evm.eosnetwork.com/

</p></details>

**Comment by stephenpdeos** [comment]
We've detected that the wallet you are attempting to use has not been configured to support EOS EVM yet. Please reference our documentation for network configuration details.

(Selection options)

[Visit docs](https://docs.eosnetwork.com/evm/quick-start/setup-metamask)

Cancel

**Comment by yarkinwho** [comment]
Currently i am using a confirm box to display message. So it would me something like:


We've detected that the wallet you are attempting to use has not been configured to support EOS EVM yet. Please reference our documentation for network configuration details.

Click OK to view the docs. 
Click Cancel to dismiss this notice.

                                                                                                                                          [Cancel button] [OK button]
                                                                                                                                          
Also I would suggest directly go to doc page instead of open in a new tab as the new tab will sometimes be blocked by pop-up blockers.

**Comment by stephenpdeos** [comment]
I would be open to testing a version with the functionality opening in a new tab since that is typically considered better UX. For external links it is a better practice IMO to open new tab. I understand the concern about popup blocker and it would be good to test the experience.

With the confirm box can we not rename the OK button option to View docs? Also better UX to inform the user what their action is being performed. Clicking OK I would not assume that something is going to happen other than dismissal of the notice.

**Comment by yarkinwho** [comment]
> Mainnet

I made a demo according to this version, please check the effect. 

Note that the problem of this version is that this will be the only warning that use the customized modal window. All other warnings will still use the default confirm box and this will somehow make some in consistency. 

If it is fine to have this inconsistency, then we can go this route. 

We can also setup other issues to change all the confirmation boxes as well... if necessary.

**Comment by stephenpdeos** [comment]
Running into an in-app error on SafePal with no console errors happening in browser
![photo_2023-10-23 22 23 42](https://github.com/eosnetworkfoundation/evm-bridge-frontend/assets/106495997/7731e277-7f4b-4569-8ed3-ca0774e5ce17)

**Comment by stephenpdeos** [comment]
Minor feedback - let's update the copy to

Header:
Missing Network Configuration in Wallet

We've detected that the wallet you are attempting to use has not been configured to support EOS EVM yet. Please use the following network information to add the network or visit our [documentation page](https://docs.eosnetwork.com/evm/quick-start/setup-metamask) for more details.

<details><summary><b>EOS EVM Mainnet</b></summary><p>

- Network Name: EOS EVM
- Chain ID: 17777
- New RPC URL: https://api.evm.eosnetwork.com/
- Currency Symbol: EOS
- Block Explorer URL (Optional): https://explorer.evm.eosnetwork.com/
- Token Bridge: https://bridge.evm.eosnetwork.com/   

</p></details>


<details><summary><b>EOS EVM Testnet</b></summary><p>

- Network Name: EOS EVM Testnet
- Chain ID: 15557
- New RPC URL: https://api.testnet.evm.eosnetwork.com/
- Currency Symbol: EOS
- Block Explorer URL (Optional): https://explorer.testnet.evm.eosnetwork.com/
- Token Bridge: https://bridge.testnet.evm.eosnetwork.com/

</p></details>
